// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: schema.proto

package rpc

import (
	encoding_binary "encoding/binary"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type StreamType int32

const (
	StreamType_NONE         StreamType = 0
	StreamType_VIDEO_RAW    StreamType = 1
	StreamType_VIDEO_PNG    StreamType = 2
	StreamType_VIDEO_JPG    StreamType = 3
	StreamType_VIDEO_H264   StreamType = 4
	StreamType_VIDEO_H265   StreamType = 5
	StreamType_FEATURES_DNN StreamType = 16
	StreamType_FEATURES_CV  StreamType = 17
	StreamType_AUDIO_PCM    StreamType = 32
	StreamType_AUDIO_MP3    StreamType = 33
	StreamType_AUDIO_OGG    StreamType = 34
	StreamType_SENSORS_RAW  StreamType = 64
)

var StreamType_name = map[int32]string{
	0:  "NONE",
	1:  "VIDEO_RAW",
	2:  "VIDEO_PNG",
	3:  "VIDEO_JPG",
	4:  "VIDEO_H264",
	5:  "VIDEO_H265",
	16: "FEATURES_DNN",
	17: "FEATURES_CV",
	32: "AUDIO_PCM",
	33: "AUDIO_MP3",
	34: "AUDIO_OGG",
	64: "SENSORS_RAW",
}

var StreamType_value = map[string]int32{
	"NONE":         0,
	"VIDEO_RAW":    1,
	"VIDEO_PNG":    2,
	"VIDEO_JPG":    3,
	"VIDEO_H264":   4,
	"VIDEO_H265":   5,
	"FEATURES_DNN": 16,
	"FEATURES_CV":  17,
	"AUDIO_PCM":    32,
	"AUDIO_MP3":    33,
	"AUDIO_OGG":    34,
	"SENSORS_RAW":  64,
}

func (x StreamType) String() string {
	return proto.EnumName(StreamType_name, int32(x))
}

func (StreamType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{0}
}

type StreamMsg struct {
	Type StreamType `protobuf:"varint,1,opt,name=Type,proto3,enum=rpc.StreamType" json:"Type,omitempty"`
	Data Blob       `protobuf:"bytes,2,opt,name=Data,proto3,customtype=Blob" json:"Data"`
}

func (m *StreamMsg) Reset()      { *m = StreamMsg{} }
func (*StreamMsg) ProtoMessage() {}
func (*StreamMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{0}
}
func (m *StreamMsg) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StreamMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StreamMsg.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StreamMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamMsg.Merge(m, src)
}
func (m *StreamMsg) XXX_Size() int {
	return m.Size()
}
func (m *StreamMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamMsg.DiscardUnknown(m)
}

var xxx_messageInfo_StreamMsg proto.InternalMessageInfo

func (m *StreamMsg) GetType() StreamType {
	if m != nil {
		return m.Type
	}
	return StreamType_NONE
}

type StatusMsg struct {
	OWD     int64   `protobuf:"varint,1,opt,name=OWD,proto3" json:"OWD,omitempty"`
	RTT     int64   `protobuf:"varint,2,opt,name=RTT,proto3" json:"RTT,omitempty"`
	Jitter  int64   `protobuf:"varint,3,opt,name=Jitter,proto3" json:"Jitter,omitempty"`
	Battery float32 `protobuf:"fixed32,4,opt,name=Battery,proto3" json:"Battery,omitempty"`
	Health  float32 `protobuf:"fixed32,5,opt,name=Health,proto3" json:"Health,omitempty"`
}

func (m *StatusMsg) Reset()      { *m = StatusMsg{} }
func (*StatusMsg) ProtoMessage() {}
func (*StatusMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{1}
}
func (m *StatusMsg) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StatusMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StatusMsg.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StatusMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusMsg.Merge(m, src)
}
func (m *StatusMsg) XXX_Size() int {
	return m.Size()
}
func (m *StatusMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusMsg.DiscardUnknown(m)
}

var xxx_messageInfo_StatusMsg proto.InternalMessageInfo

func (m *StatusMsg) GetOWD() int64 {
	if m != nil {
		return m.OWD
	}
	return 0
}

func (m *StatusMsg) GetRTT() int64 {
	if m != nil {
		return m.RTT
	}
	return 0
}

func (m *StatusMsg) GetJitter() int64 {
	if m != nil {
		return m.Jitter
	}
	return 0
}

func (m *StatusMsg) GetBattery() float32 {
	if m != nil {
		return m.Battery
	}
	return 0
}

func (m *StatusMsg) GetHealth() float32 {
	if m != nil {
		return m.Health
	}
	return 0
}

type ChatMsg struct {
	Timestamp int64  `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Username  string `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	Message   string `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (m *ChatMsg) Reset()      { *m = ChatMsg{} }
func (*ChatMsg) ProtoMessage() {}
func (*ChatMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{2}
}
func (m *ChatMsg) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ChatMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ChatMsg.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ChatMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatMsg.Merge(m, src)
}
func (m *ChatMsg) XXX_Size() int {
	return m.Size()
}
func (m *ChatMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ChatMsg proto.InternalMessageInfo

func (m *ChatMsg) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ChatMsg) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ChatMsg) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type EventMsg struct {
	Id    uint64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Flags []uint64  `protobuf:"varint,2,rep,packed,name=Flags,proto3" json:"Flags,omitempty"`
	Data  []float32 `protobuf:"fixed32,3,rep,packed,name=Data,proto3" json:"Data,omitempty"`
}

func (m *EventMsg) Reset()      { *m = EventMsg{} }
func (*EventMsg) ProtoMessage() {}
func (*EventMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{3}
}
func (m *EventMsg) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventMsg.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventMsg.Merge(m, src)
}
func (m *EventMsg) XXX_Size() int {
	return m.Size()
}
func (m *EventMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_EventMsg.DiscardUnknown(m)
}

var xxx_messageInfo_EventMsg proto.InternalMessageInfo

func (m *EventMsg) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *EventMsg) GetFlags() []uint64 {
	if m != nil {
		return m.Flags
	}
	return nil
}

func (m *EventMsg) GetData() []float32 {
	if m != nil {
		return m.Data
	}
	return nil
}

type RobotMsg struct {
	Id           string                `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name         string                `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Description  string                `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	Capabilities []RobotMsg_Capability `protobuf:"bytes,4,rep,name=Capabilities,proto3" json:"Capabilities"`
}

func (m *RobotMsg) Reset()      { *m = RobotMsg{} }
func (*RobotMsg) ProtoMessage() {}
func (*RobotMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{4}
}
func (m *RobotMsg) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RobotMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RobotMsg.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RobotMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RobotMsg.Merge(m, src)
}
func (m *RobotMsg) XXX_Size() int {
	return m.Size()
}
func (m *RobotMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_RobotMsg.DiscardUnknown(m)
}

var xxx_messageInfo_RobotMsg proto.InternalMessageInfo

func (m *RobotMsg) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RobotMsg) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RobotMsg) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *RobotMsg) GetCapabilities() []RobotMsg_Capability {
	if m != nil {
		return m.Capabilities
	}
	return nil
}

type RobotMsg_Capability struct {
	// NOTE:
	// Negative Id refers to stream types:
	//   streamType: abs(Id)
	// Positive Id refers to Event types.
	Id          int64  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
}

func (m *RobotMsg_Capability) Reset()      { *m = RobotMsg_Capability{} }
func (*RobotMsg_Capability) ProtoMessage() {}
func (*RobotMsg_Capability) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{4, 0}
}
func (m *RobotMsg_Capability) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RobotMsg_Capability) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RobotMsg_Capability.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RobotMsg_Capability) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RobotMsg_Capability.Merge(m, src)
}
func (m *RobotMsg_Capability) XXX_Size() int {
	return m.Size()
}
func (m *RobotMsg_Capability) XXX_DiscardUnknown() {
	xxx_messageInfo_RobotMsg_Capability.DiscardUnknown(m)
}

var xxx_messageInfo_RobotMsg_Capability proto.InternalMessageInfo

func (m *RobotMsg_Capability) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RobotMsg_Capability) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RobotMsg_Capability) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

// Message coming from the robot
type Robot struct {
	Timestamp int64       `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Robot     RobotMsg    `protobuf:"bytes,2,opt,name=Robot,proto3" json:"Robot"`
	Status    StatusMsg   `protobuf:"bytes,3,opt,name=Status,proto3" json:"Status"`
	Stream    []StreamMsg `protobuf:"bytes,4,rep,name=Stream,proto3" json:"Stream"`
}

func (m *Robot) Reset()      { *m = Robot{} }
func (*Robot) ProtoMessage() {}
func (*Robot) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{5}
}
func (m *Robot) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Robot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Robot.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Robot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Robot.Merge(m, src)
}
func (m *Robot) XXX_Size() int {
	return m.Size()
}
func (m *Robot) XXX_DiscardUnknown() {
	xxx_messageInfo_Robot.DiscardUnknown(m)
}

var xxx_messageInfo_Robot proto.InternalMessageInfo

func (m *Robot) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Robot) GetRobot() RobotMsg {
	if m != nil {
		return m.Robot
	}
	return RobotMsg{}
}

func (m *Robot) GetStatus() StatusMsg {
	if m != nil {
		return m.Status
	}
	return StatusMsg{}
}

func (m *Robot) GetStream() []StreamMsg {
	if m != nil {
		return m.Stream
	}
	return nil
}

// Message coming from either the Governor or Operator
type Operator struct {
	Timestamp int64       `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	OWD       int64       `protobuf:"varint,2,opt,name=OWD,proto3" json:"OWD,omitempty"`
	Stream    []StreamMsg `protobuf:"bytes,3,rep,name=Stream,proto3" json:"Stream"`
	Events    []EventMsg  `protobuf:"bytes,5,rep,name=Events,proto3" json:"Events"`
}

func (m *Operator) Reset()      { *m = Operator{} }
func (*Operator) ProtoMessage() {}
func (*Operator) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{6}
}
func (m *Operator) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Operator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Operator.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Operator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Operator.Merge(m, src)
}
func (m *Operator) XXX_Size() int {
	return m.Size()
}
func (m *Operator) XXX_DiscardUnknown() {
	xxx_messageInfo_Operator.DiscardUnknown(m)
}

var xxx_messageInfo_Operator proto.InternalMessageInfo

func (m *Operator) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Operator) GetOWD() int64 {
	if m != nil {
		return m.OWD
	}
	return 0
}

func (m *Operator) GetStream() []StreamMsg {
	if m != nil {
		return m.Stream
	}
	return nil
}

func (m *Operator) GetEvents() []EventMsg {
	if m != nil {
		return m.Events
	}
	return nil
}

func init() {
	proto.RegisterEnum("rpc.StreamType", StreamType_name, StreamType_value)
	proto.RegisterType((*StreamMsg)(nil), "rpc.StreamMsg")
	proto.RegisterType((*StatusMsg)(nil), "rpc.StatusMsg")
	proto.RegisterType((*ChatMsg)(nil), "rpc.ChatMsg")
	proto.RegisterType((*EventMsg)(nil), "rpc.EventMsg")
	proto.RegisterType((*RobotMsg)(nil), "rpc.RobotMsg")
	proto.RegisterType((*RobotMsg_Capability)(nil), "rpc.RobotMsg.Capability")
	proto.RegisterType((*Robot)(nil), "rpc.Robot")
	proto.RegisterType((*Operator)(nil), "rpc.Operator")
}

func init() { proto.RegisterFile("schema.proto", fileDescriptor_1c5fb4d8cc22d66a) }

var fileDescriptor_1c5fb4d8cc22d66a = []byte{
	// 689 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x3d, 0x4f, 0x1b, 0x4b,
	0x14, 0xf5, 0xec, 0xae, 0x8d, 0x7d, 0x6d, 0xcc, 0xbc, 0xd1, 0xd3, 0xd3, 0x0a, 0x3d, 0x2d, 0xfb,
	0xfc, 0x1a, 0xe7, 0x43, 0x46, 0x31, 0x24, 0x35, 0xf8, 0x03, 0x63, 0x24, 0x7f, 0x68, 0x6c, 0xa0,
	0x8a, 0xd0, 0xd8, 0x4c, 0xec, 0x95, 0x6c, 0x76, 0xb5, 0xbb, 0x20, 0xb9, 0xcb, 0x4f, 0x48, 0x93,
	0xff, 0x90, 0x22, 0x3f, 0x20, 0x65, 0x8a, 0x14, 0x94, 0x94, 0x28, 0x05, 0x0a, 0xa6, 0x49, 0x99,
	0x32, 0x65, 0x34, 0xb3, 0x63, 0x16, 0xa7, 0x41, 0x4a, 0x37, 0xe7, 0xde, 0x73, 0xcf, 0x3d, 0x9e,
	0x39, 0x5e, 0xc8, 0x05, 0xc3, 0x31, 0x9f, 0xb2, 0x92, 0xe7, 0xbb, 0xa1, 0x4b, 0x74, 0xdf, 0x1b,
	0xae, 0x6f, 0x8f, 0x9c, 0x70, 0x7c, 0x3e, 0x28, 0x0d, 0xdd, 0xe9, 0xe6, 0xc8, 0x1d, 0xb9, 0x9b,
	0xb2, 0x37, 0x38, 0x7f, 0xb3, 0x73, 0xf1, 0xa2, 0xb4, 0x55, 0x2a, 0xcb, 0xa2, 0xac, 0xc9, 0x53,
	0x34, 0x5a, 0xa0, 0x90, 0xe9, 0x85, 0x3e, 0x67, 0xd3, 0x56, 0x30, 0x22, 0xff, 0x83, 0xd1, 0x9f,
	0x79, 0xdc, 0x44, 0x36, 0x2a, 0xe6, 0xcb, 0x6b, 0x25, 0xdf, 0x1b, 0x96, 0xa2, 0xae, 0x28, 0x53,
	0xd9, 0x24, 0x36, 0x18, 0x35, 0x16, 0x32, 0x53, 0xb3, 0x51, 0x31, 0x57, 0xc9, 0x5d, 0xde, 0x6c,
	0x24, 0xbe, 0xde, 0x6c, 0x18, 0x95, 0x89, 0x3b, 0xa0, 0xb2, 0x53, 0x98, 0x09, 0x4d, 0x16, 0x9e,
	0x07, 0x42, 0x13, 0x83, 0xde, 0x39, 0xae, 0x49, 0x49, 0x9d, 0x8a, 0xa3, 0xa8, 0xd0, 0x7e, 0x5f,
	0xce, 0xeb, 0x54, 0x1c, 0xc9, 0x3f, 0x90, 0x3a, 0x70, 0xc2, 0x90, 0xfb, 0xa6, 0x2e, 0x8b, 0x0a,
	0x11, 0x13, 0x56, 0x2a, 0x4c, 0x9c, 0x66, 0xa6, 0x61, 0xa3, 0xa2, 0x46, 0x17, 0x50, 0x4c, 0xec,
	0x73, 0x36, 0x09, 0xc7, 0x66, 0x52, 0x36, 0x14, 0x2a, 0xbc, 0x86, 0x95, 0xea, 0x98, 0x85, 0x62,
	0xf1, 0xbf, 0x90, 0xe9, 0x3b, 0x53, 0x1e, 0x84, 0x6c, 0xea, 0xa9, 0xf5, 0x71, 0x81, 0xac, 0x43,
	0xfa, 0x30, 0xe0, 0xfe, 0x19, 0x9b, 0x72, 0xe9, 0x24, 0x43, 0xef, 0xb1, 0x58, 0xdb, 0xe2, 0x41,
	0xc0, 0x46, 0x5c, 0xfa, 0xc9, 0xd0, 0x05, 0x2c, 0xd4, 0x20, 0x5d, 0xbf, 0xe0, 0x67, 0x52, 0x3f,
	0x0f, 0x5a, 0xf3, 0x54, 0x0a, 0x1b, 0x54, 0x6b, 0x9e, 0x92, 0xbf, 0x21, 0xb9, 0x37, 0x61, 0xa3,
	0xc0, 0xd4, 0x6c, 0xbd, 0x68, 0xd0, 0x08, 0x10, 0xa2, 0x6e, 0x4b, 0xb7, 0xf5, 0xa2, 0xa6, 0xee,
	0xe7, 0x3b, 0x82, 0x34, 0x75, 0x07, 0xee, 0x6f, 0x32, 0x19, 0x29, 0x43, 0xc0, 0x68, 0xc7, 0xa6,
	0xe4, 0x99, 0xd8, 0x90, 0xad, 0xf1, 0x60, 0xe8, 0x3b, 0x5e, 0xe8, 0xb8, 0x67, 0xca, 0xd4, 0xc3,
	0x12, 0xa9, 0x40, 0xae, 0xca, 0x3c, 0x36, 0x70, 0x26, 0x4e, 0xe8, 0xf0, 0xc0, 0x34, 0x6c, 0xbd,
	0x98, 0x2d, 0x9b, 0xf2, 0x05, 0x17, 0xab, 0x4a, 0xf7, 0x8c, 0x59, 0xc5, 0x10, 0xcf, 0x46, 0x97,
	0x66, 0xd6, 0x29, 0x40, 0xcc, 0x78, 0xe0, 0x4b, 0xff, 0x73, 0x5f, 0x85, 0x8f, 0x08, 0x92, 0x72,
	0xff, 0x23, 0xcf, 0xf1, 0x44, 0xd1, 0xa4, 0x7c, 0xb6, 0xbc, 0xba, 0x64, 0x5c, 0xb9, 0x55, 0x42,
	0xcf, 0x21, 0x15, 0xa5, 0x4b, 0xee, 0xcb, 0x96, 0xf3, 0x2a, 0xa6, 0x2a, 0x70, 0x8a, 0xac, 0x38,
	0x11, 0x5b, 0x24, 0x58, 0x5d, 0x49, 0xfe, 0x41, 0xa8, 0x97, 0xd8, 0xa2, 0x50, 0x78, 0x8f, 0x20,
	0xdd, 0xf1, 0xb8, 0xcf, 0x42, 0xd7, 0x7f, 0xc4, 0xb1, 0xca, 0xb5, 0x16, 0xe7, 0x3a, 0x5e, 0xa5,
	0x3f, 0xbe, 0x8a, 0x3c, 0x83, 0x94, 0x8c, 0x52, 0x60, 0x26, 0x25, 0x3b, 0xfa, 0xc9, 0x8b, 0x74,
	0x2d, 0xc8, 0x11, 0xe5, 0xe9, 0x17, 0x04, 0x10, 0xff, 0x11, 0x49, 0x1a, 0x8c, 0x76, 0xa7, 0x5d,
	0xc7, 0x09, 0xb2, 0x0a, 0x99, 0xa3, 0x66, 0xad, 0xde, 0x39, 0xa1, 0xbb, 0xc7, 0x18, 0xc5, 0xb0,
	0xdb, 0x6e, 0x60, 0x2d, 0x86, 0x07, 0xdd, 0x06, 0xd6, 0x49, 0x1e, 0x20, 0x82, 0xfb, 0xe5, 0x57,
	0xdb, 0xd8, 0x58, 0xc2, 0x2f, 0x71, 0x92, 0x60, 0xc8, 0xed, 0xd5, 0x77, 0xfb, 0x87, 0xb4, 0xde,
	0x3b, 0xa9, 0xb5, 0xdb, 0x18, 0x93, 0x35, 0xc8, 0xde, 0x57, 0xaa, 0x47, 0xf8, 0x2f, 0xa1, 0xb8,
	0x7b, 0x58, 0x6b, 0x76, 0x4e, 0xba, 0xd5, 0x16, 0xb6, 0x63, 0xd8, 0xea, 0x6e, 0xe1, 0xff, 0x62,
	0xd8, 0x69, 0x34, 0x70, 0x41, 0x4c, 0xf7, 0xea, 0xed, 0x5e, 0x87, 0xf6, 0xa4, 0xbd, 0x9d, 0xca,
	0xf6, 0xf5, 0xad, 0x95, 0xf8, 0x71, 0x6b, 0xa1, 0x9f, 0xb7, 0x16, 0x7a, 0x3b, 0xb7, 0xd0, 0x87,
	0xb9, 0x85, 0x3e, 0xcd, 0x2d, 0xf4, 0x79, 0x6e, 0xa1, 0xcb, 0xb9, 0x85, 0xae, 0xe6, 0x16, 0xfa,
	0x36, 0xb7, 0xd0, 0xbb, 0x3b, 0x2b, 0x71, 0x75, 0x67, 0x25, 0xae, 0xef, 0xac, 0xc4, 0x20, 0x25,
	0xbf, 0x54, 0x5b, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x58, 0x3f, 0x75, 0x77, 0xf4, 0x04, 0x00,
	0x00,
}

func (this *StreamMsg) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*StreamMsg)
	if !ok {
		that2, ok := that.(StreamMsg)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Type != that1.Type {
		return false
	}
	if !this.Data.Equal(that1.Data) {
		return false
	}
	return true
}
func (this *StatusMsg) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*StatusMsg)
	if !ok {
		that2, ok := that.(StatusMsg)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.OWD != that1.OWD {
		return false
	}
	if this.RTT != that1.RTT {
		return false
	}
	if this.Jitter != that1.Jitter {
		return false
	}
	if this.Battery != that1.Battery {
		return false
	}
	if this.Health != that1.Health {
		return false
	}
	return true
}
func (this *ChatMsg) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ChatMsg)
	if !ok {
		that2, ok := that.(ChatMsg)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Timestamp != that1.Timestamp {
		return false
	}
	if this.Username != that1.Username {
		return false
	}
	if this.Message != that1.Message {
		return false
	}
	return true
}
func (this *EventMsg) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*EventMsg)
	if !ok {
		that2, ok := that.(EventMsg)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Id != that1.Id {
		return false
	}
	if len(this.Flags) != len(that1.Flags) {
		return false
	}
	for i := range this.Flags {
		if this.Flags[i] != that1.Flags[i] {
			return false
		}
	}
	if len(this.Data) != len(that1.Data) {
		return false
	}
	for i := range this.Data {
		if this.Data[i] != that1.Data[i] {
			return false
		}
	}
	return true
}
func (this *RobotMsg) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*RobotMsg)
	if !ok {
		that2, ok := that.(RobotMsg)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Id != that1.Id {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if this.Description != that1.Description {
		return false
	}
	if len(this.Capabilities) != len(that1.Capabilities) {
		return false
	}
	for i := range this.Capabilities {
		if !this.Capabilities[i].Equal(&that1.Capabilities[i]) {
			return false
		}
	}
	return true
}
func (this *RobotMsg_Capability) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*RobotMsg_Capability)
	if !ok {
		that2, ok := that.(RobotMsg_Capability)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Id != that1.Id {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if this.Description != that1.Description {
		return false
	}
	return true
}
func (this *Robot) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Robot)
	if !ok {
		that2, ok := that.(Robot)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Timestamp != that1.Timestamp {
		return false
	}
	if !this.Robot.Equal(&that1.Robot) {
		return false
	}
	if !this.Status.Equal(&that1.Status) {
		return false
	}
	if len(this.Stream) != len(that1.Stream) {
		return false
	}
	for i := range this.Stream {
		if !this.Stream[i].Equal(&that1.Stream[i]) {
			return false
		}
	}
	return true
}
func (this *Operator) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Operator)
	if !ok {
		that2, ok := that.(Operator)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Timestamp != that1.Timestamp {
		return false
	}
	if this.OWD != that1.OWD {
		return false
	}
	if len(this.Stream) != len(that1.Stream) {
		return false
	}
	for i := range this.Stream {
		if !this.Stream[i].Equal(&that1.Stream[i]) {
			return false
		}
	}
	if len(this.Events) != len(that1.Events) {
		return false
	}
	for i := range this.Events {
		if !this.Events[i].Equal(&that1.Events[i]) {
			return false
		}
	}
	return true
}
func (this *StreamMsg) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&rpc.StreamMsg{")
	s = append(s, "Type: "+fmt.Sprintf("%#v", this.Type)+",\n")
	s = append(s, "Data: "+fmt.Sprintf("%#v", this.Data)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *StatusMsg) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 9)
	s = append(s, "&rpc.StatusMsg{")
	s = append(s, "OWD: "+fmt.Sprintf("%#v", this.OWD)+",\n")
	s = append(s, "RTT: "+fmt.Sprintf("%#v", this.RTT)+",\n")
	s = append(s, "Jitter: "+fmt.Sprintf("%#v", this.Jitter)+",\n")
	s = append(s, "Battery: "+fmt.Sprintf("%#v", this.Battery)+",\n")
	s = append(s, "Health: "+fmt.Sprintf("%#v", this.Health)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *ChatMsg) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&rpc.ChatMsg{")
	s = append(s, "Timestamp: "+fmt.Sprintf("%#v", this.Timestamp)+",\n")
	s = append(s, "Username: "+fmt.Sprintf("%#v", this.Username)+",\n")
	s = append(s, "Message: "+fmt.Sprintf("%#v", this.Message)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *EventMsg) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&rpc.EventMsg{")
	s = append(s, "Id: "+fmt.Sprintf("%#v", this.Id)+",\n")
	s = append(s, "Flags: "+fmt.Sprintf("%#v", this.Flags)+",\n")
	s = append(s, "Data: "+fmt.Sprintf("%#v", this.Data)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *RobotMsg) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 8)
	s = append(s, "&rpc.RobotMsg{")
	s = append(s, "Id: "+fmt.Sprintf("%#v", this.Id)+",\n")
	s = append(s, "Name: "+fmt.Sprintf("%#v", this.Name)+",\n")
	s = append(s, "Description: "+fmt.Sprintf("%#v", this.Description)+",\n")
	if this.Capabilities != nil {
		vs := make([]RobotMsg_Capability, len(this.Capabilities))
		for i := range vs {
			vs[i] = this.Capabilities[i]
		}
		s = append(s, "Capabilities: "+fmt.Sprintf("%#v", vs)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *RobotMsg_Capability) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&rpc.RobotMsg_Capability{")
	s = append(s, "Id: "+fmt.Sprintf("%#v", this.Id)+",\n")
	s = append(s, "Name: "+fmt.Sprintf("%#v", this.Name)+",\n")
	s = append(s, "Description: "+fmt.Sprintf("%#v", this.Description)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *Robot) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 8)
	s = append(s, "&rpc.Robot{")
	s = append(s, "Timestamp: "+fmt.Sprintf("%#v", this.Timestamp)+",\n")
	s = append(s, "Robot: "+strings.Replace(this.Robot.GoString(), `&`, ``, 1)+",\n")
	s = append(s, "Status: "+strings.Replace(this.Status.GoString(), `&`, ``, 1)+",\n")
	if this.Stream != nil {
		vs := make([]StreamMsg, len(this.Stream))
		for i := range vs {
			vs[i] = this.Stream[i]
		}
		s = append(s, "Stream: "+fmt.Sprintf("%#v", vs)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *Operator) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 8)
	s = append(s, "&rpc.Operator{")
	s = append(s, "Timestamp: "+fmt.Sprintf("%#v", this.Timestamp)+",\n")
	s = append(s, "OWD: "+fmt.Sprintf("%#v", this.OWD)+",\n")
	if this.Stream != nil {
		vs := make([]StreamMsg, len(this.Stream))
		for i := range vs {
			vs[i] = this.Stream[i]
		}
		s = append(s, "Stream: "+fmt.Sprintf("%#v", vs)+",\n")
	}
	if this.Events != nil {
		vs := make([]EventMsg, len(this.Events))
		for i := range vs {
			vs[i] = this.Events[i]
		}
		s = append(s, "Events: "+fmt.Sprintf("%#v", vs)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringSchema(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *StreamMsg) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StreamMsg) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StreamMsg) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Data.Size()
		i -= size
		if _, err := m.Data.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintSchema(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.Type != 0 {
		i = encodeVarintSchema(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *StatusMsg) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StatusMsg) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StatusMsg) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Health != 0 {
		i -= 4
		encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(m.Health))))
		i--
		dAtA[i] = 0x2d
	}
	if m.Battery != 0 {
		i -= 4
		encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(m.Battery))))
		i--
		dAtA[i] = 0x25
	}
	if m.Jitter != 0 {
		i = encodeVarintSchema(dAtA, i, uint64(m.Jitter))
		i--
		dAtA[i] = 0x18
	}
	if m.RTT != 0 {
		i = encodeVarintSchema(dAtA, i, uint64(m.RTT))
		i--
		dAtA[i] = 0x10
	}
	if m.OWD != 0 {
		i = encodeVarintSchema(dAtA, i, uint64(m.OWD))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ChatMsg) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ChatMsg) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ChatMsg) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Message) > 0 {
		i -= len(m.Message)
		copy(dAtA[i:], m.Message)
		i = encodeVarintSchema(dAtA, i, uint64(len(m.Message)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Username) > 0 {
		i -= len(m.Username)
		copy(dAtA[i:], m.Username)
		i = encodeVarintSchema(dAtA, i, uint64(len(m.Username)))
		i--
		dAtA[i] = 0x12
	}
	if m.Timestamp != 0 {
		i = encodeVarintSchema(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *EventMsg) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventMsg) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventMsg) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Data) > 0 {
		for iNdEx := len(m.Data) - 1; iNdEx >= 0; iNdEx-- {
			f1 := math.Float32bits(float32(m.Data[iNdEx]))
			i -= 4
			encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(f1))
		}
		i = encodeVarintSchema(dAtA, i, uint64(len(m.Data)*4))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Flags) > 0 {
		dAtA3 := make([]byte, len(m.Flags)*10)
		var j2 int
		for _, num := range m.Flags {
			for num >= 1<<7 {
				dAtA3[j2] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j2++
			}
			dAtA3[j2] = uint8(num)
			j2++
		}
		i -= j2
		copy(dAtA[i:], dAtA3[:j2])
		i = encodeVarintSchema(dAtA, i, uint64(j2))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintSchema(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *RobotMsg) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RobotMsg) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RobotMsg) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Capabilities) > 0 {
		for iNdEx := len(m.Capabilities) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Capabilities[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSchema(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintSchema(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintSchema(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintSchema(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RobotMsg_Capability) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RobotMsg_Capability) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RobotMsg_Capability) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintSchema(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintSchema(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintSchema(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Robot) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Robot) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Robot) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Stream) > 0 {
		for iNdEx := len(m.Stream) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Stream[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSchema(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	{
		size, err := m.Status.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintSchema(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.Robot.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintSchema(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.Timestamp != 0 {
		i = encodeVarintSchema(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Operator) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Operator) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Operator) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Events) > 0 {
		for iNdEx := len(m.Events) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Events[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSchema(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Stream) > 0 {
		for iNdEx := len(m.Stream) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Stream[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSchema(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.OWD != 0 {
		i = encodeVarintSchema(dAtA, i, uint64(m.OWD))
		i--
		dAtA[i] = 0x10
	}
	if m.Timestamp != 0 {
		i = encodeVarintSchema(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintSchema(dAtA []byte, offset int, v uint64) int {
	offset -= sovSchema(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func NewPopulatedStreamMsg(r randySchema, easy bool) *StreamMsg {
	this := &StreamMsg{}
	this.Type = StreamType([]int32{0, 1, 2, 3, 4, 5, 16, 17, 32, 33, 34, 64}[r.Intn(12)])
	v1 := NewPopulatedBlob(r)
	this.Data = *v1
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedStatusMsg(r randySchema, easy bool) *StatusMsg {
	this := &StatusMsg{}
	this.OWD = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.OWD *= -1
	}
	this.RTT = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.RTT *= -1
	}
	this.Jitter = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.Jitter *= -1
	}
	this.Battery = float32(r.Float32())
	if r.Intn(2) == 0 {
		this.Battery *= -1
	}
	this.Health = float32(r.Float32())
	if r.Intn(2) == 0 {
		this.Health *= -1
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedChatMsg(r randySchema, easy bool) *ChatMsg {
	this := &ChatMsg{}
	this.Timestamp = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.Timestamp *= -1
	}
	this.Username = string(randStringSchema(r))
	this.Message = string(randStringSchema(r))
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedEventMsg(r randySchema, easy bool) *EventMsg {
	this := &EventMsg{}
	this.Id = uint64(uint64(r.Uint32()))
	v2 := r.Intn(10)
	this.Flags = make([]uint64, v2)
	for i := 0; i < v2; i++ {
		this.Flags[i] = uint64(uint64(r.Uint32()))
	}
	v3 := r.Intn(10)
	this.Data = make([]float32, v3)
	for i := 0; i < v3; i++ {
		this.Data[i] = float32(r.Float32())
		if r.Intn(2) == 0 {
			this.Data[i] *= -1
		}
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedRobotMsg(r randySchema, easy bool) *RobotMsg {
	this := &RobotMsg{}
	this.Id = string(randStringSchema(r))
	this.Name = string(randStringSchema(r))
	this.Description = string(randStringSchema(r))
	if r.Intn(5) != 0 {
		v4 := r.Intn(5)
		this.Capabilities = make([]RobotMsg_Capability, v4)
		for i := 0; i < v4; i++ {
			v5 := NewPopulatedRobotMsg_Capability(r, easy)
			this.Capabilities[i] = *v5
		}
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedRobotMsg_Capability(r randySchema, easy bool) *RobotMsg_Capability {
	this := &RobotMsg_Capability{}
	this.Id = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.Id *= -1
	}
	this.Name = string(randStringSchema(r))
	this.Description = string(randStringSchema(r))
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedRobot(r randySchema, easy bool) *Robot {
	this := &Robot{}
	this.Timestamp = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.Timestamp *= -1
	}
	v6 := NewPopulatedRobotMsg(r, easy)
	this.Robot = *v6
	v7 := NewPopulatedStatusMsg(r, easy)
	this.Status = *v7
	if r.Intn(5) != 0 {
		v8 := r.Intn(5)
		this.Stream = make([]StreamMsg, v8)
		for i := 0; i < v8; i++ {
			v9 := NewPopulatedStreamMsg(r, easy)
			this.Stream[i] = *v9
		}
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedOperator(r randySchema, easy bool) *Operator {
	this := &Operator{}
	this.Timestamp = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.Timestamp *= -1
	}
	this.OWD = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.OWD *= -1
	}
	if r.Intn(5) != 0 {
		v10 := r.Intn(5)
		this.Stream = make([]StreamMsg, v10)
		for i := 0; i < v10; i++ {
			v11 := NewPopulatedStreamMsg(r, easy)
			this.Stream[i] = *v11
		}
	}
	if r.Intn(5) != 0 {
		v12 := r.Intn(5)
		this.Events = make([]EventMsg, v12)
		for i := 0; i < v12; i++ {
			v13 := NewPopulatedEventMsg(r, easy)
			this.Events[i] = *v13
		}
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

type randySchema interface {
	Float32() float32
	Float64() float64
	Int63() int64
	Int31() int32
	Uint32() uint32
	Intn(n int) int
}

func randUTF8RuneSchema(r randySchema) rune {
	ru := r.Intn(62)
	if ru < 10 {
		return rune(ru + 48)
	} else if ru < 36 {
		return rune(ru + 55)
	}
	return rune(ru + 61)
}
func randStringSchema(r randySchema) string {
	v14 := r.Intn(100)
	tmps := make([]rune, v14)
	for i := 0; i < v14; i++ {
		tmps[i] = randUTF8RuneSchema(r)
	}
	return string(tmps)
}
func randUnrecognizedSchema(r randySchema, maxFieldNumber int) (dAtA []byte) {
	l := r.Intn(5)
	for i := 0; i < l; i++ {
		wire := r.Intn(4)
		if wire == 3 {
			wire = 5
		}
		fieldNumber := maxFieldNumber + r.Intn(100)
		dAtA = randFieldSchema(dAtA, r, fieldNumber, wire)
	}
	return dAtA
}
func randFieldSchema(dAtA []byte, r randySchema, fieldNumber int, wire int) []byte {
	key := uint32(fieldNumber)<<3 | uint32(wire)
	switch wire {
	case 0:
		dAtA = encodeVarintPopulateSchema(dAtA, uint64(key))
		v15 := r.Int63()
		if r.Intn(2) == 0 {
			v15 *= -1
		}
		dAtA = encodeVarintPopulateSchema(dAtA, uint64(v15))
	case 1:
		dAtA = encodeVarintPopulateSchema(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	case 2:
		dAtA = encodeVarintPopulateSchema(dAtA, uint64(key))
		ll := r.Intn(100)
		dAtA = encodeVarintPopulateSchema(dAtA, uint64(ll))
		for j := 0; j < ll; j++ {
			dAtA = append(dAtA, byte(r.Intn(256)))
		}
	default:
		dAtA = encodeVarintPopulateSchema(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	}
	return dAtA
}
func encodeVarintPopulateSchema(dAtA []byte, v uint64) []byte {
	for v >= 1<<7 {
		dAtA = append(dAtA, uint8(uint64(v)&0x7f|0x80))
		v >>= 7
	}
	dAtA = append(dAtA, uint8(v))
	return dAtA
}
func (m *StreamMsg) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Type != 0 {
		n += 1 + sovSchema(uint64(m.Type))
	}
	l = m.Data.Size()
	n += 1 + l + sovSchema(uint64(l))
	return n
}

func (m *StatusMsg) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.OWD != 0 {
		n += 1 + sovSchema(uint64(m.OWD))
	}
	if m.RTT != 0 {
		n += 1 + sovSchema(uint64(m.RTT))
	}
	if m.Jitter != 0 {
		n += 1 + sovSchema(uint64(m.Jitter))
	}
	if m.Battery != 0 {
		n += 5
	}
	if m.Health != 0 {
		n += 5
	}
	return n
}

func (m *ChatMsg) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Timestamp != 0 {
		n += 1 + sovSchema(uint64(m.Timestamp))
	}
	l = len(m.Username)
	if l > 0 {
		n += 1 + l + sovSchema(uint64(l))
	}
	l = len(m.Message)
	if l > 0 {
		n += 1 + l + sovSchema(uint64(l))
	}
	return n
}

func (m *EventMsg) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovSchema(uint64(m.Id))
	}
	if len(m.Flags) > 0 {
		l = 0
		for _, e := range m.Flags {
			l += sovSchema(uint64(e))
		}
		n += 1 + sovSchema(uint64(l)) + l
	}
	if len(m.Data) > 0 {
		n += 1 + sovSchema(uint64(len(m.Data)*4)) + len(m.Data)*4
	}
	return n
}

func (m *RobotMsg) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovSchema(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovSchema(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovSchema(uint64(l))
	}
	if len(m.Capabilities) > 0 {
		for _, e := range m.Capabilities {
			l = e.Size()
			n += 1 + l + sovSchema(uint64(l))
		}
	}
	return n
}

func (m *RobotMsg_Capability) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovSchema(uint64(m.Id))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovSchema(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovSchema(uint64(l))
	}
	return n
}

func (m *Robot) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Timestamp != 0 {
		n += 1 + sovSchema(uint64(m.Timestamp))
	}
	l = m.Robot.Size()
	n += 1 + l + sovSchema(uint64(l))
	l = m.Status.Size()
	n += 1 + l + sovSchema(uint64(l))
	if len(m.Stream) > 0 {
		for _, e := range m.Stream {
			l = e.Size()
			n += 1 + l + sovSchema(uint64(l))
		}
	}
	return n
}

func (m *Operator) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Timestamp != 0 {
		n += 1 + sovSchema(uint64(m.Timestamp))
	}
	if m.OWD != 0 {
		n += 1 + sovSchema(uint64(m.OWD))
	}
	if len(m.Stream) > 0 {
		for _, e := range m.Stream {
			l = e.Size()
			n += 1 + l + sovSchema(uint64(l))
		}
	}
	if len(m.Events) > 0 {
		for _, e := range m.Events {
			l = e.Size()
			n += 1 + l + sovSchema(uint64(l))
		}
	}
	return n
}

func sovSchema(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSchema(x uint64) (n int) {
	return sovSchema(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *StreamMsg) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&StreamMsg{`,
		`Type:` + fmt.Sprintf("%v", this.Type) + `,`,
		`Data:` + fmt.Sprintf("%v", this.Data) + `,`,
		`}`,
	}, "")
	return s
}
func (this *StatusMsg) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&StatusMsg{`,
		`OWD:` + fmt.Sprintf("%v", this.OWD) + `,`,
		`RTT:` + fmt.Sprintf("%v", this.RTT) + `,`,
		`Jitter:` + fmt.Sprintf("%v", this.Jitter) + `,`,
		`Battery:` + fmt.Sprintf("%v", this.Battery) + `,`,
		`Health:` + fmt.Sprintf("%v", this.Health) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ChatMsg) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ChatMsg{`,
		`Timestamp:` + fmt.Sprintf("%v", this.Timestamp) + `,`,
		`Username:` + fmt.Sprintf("%v", this.Username) + `,`,
		`Message:` + fmt.Sprintf("%v", this.Message) + `,`,
		`}`,
	}, "")
	return s
}
func (this *EventMsg) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&EventMsg{`,
		`Id:` + fmt.Sprintf("%v", this.Id) + `,`,
		`Flags:` + fmt.Sprintf("%v", this.Flags) + `,`,
		`Data:` + fmt.Sprintf("%v", this.Data) + `,`,
		`}`,
	}, "")
	return s
}
func (this *RobotMsg) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForCapabilities := "[]RobotMsg_Capability{"
	for _, f := range this.Capabilities {
		repeatedStringForCapabilities += fmt.Sprintf("%v", f) + ","
	}
	repeatedStringForCapabilities += "}"
	s := strings.Join([]string{`&RobotMsg{`,
		`Id:` + fmt.Sprintf("%v", this.Id) + `,`,
		`Name:` + fmt.Sprintf("%v", this.Name) + `,`,
		`Description:` + fmt.Sprintf("%v", this.Description) + `,`,
		`Capabilities:` + repeatedStringForCapabilities + `,`,
		`}`,
	}, "")
	return s
}
func (this *RobotMsg_Capability) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&RobotMsg_Capability{`,
		`Id:` + fmt.Sprintf("%v", this.Id) + `,`,
		`Name:` + fmt.Sprintf("%v", this.Name) + `,`,
		`Description:` + fmt.Sprintf("%v", this.Description) + `,`,
		`}`,
	}, "")
	return s
}
func (this *Robot) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForStream := "[]StreamMsg{"
	for _, f := range this.Stream {
		repeatedStringForStream += strings.Replace(strings.Replace(f.String(), "StreamMsg", "StreamMsg", 1), `&`, ``, 1) + ","
	}
	repeatedStringForStream += "}"
	s := strings.Join([]string{`&Robot{`,
		`Timestamp:` + fmt.Sprintf("%v", this.Timestamp) + `,`,
		`Robot:` + strings.Replace(strings.Replace(this.Robot.String(), "RobotMsg", "RobotMsg", 1), `&`, ``, 1) + `,`,
		`Status:` + strings.Replace(strings.Replace(this.Status.String(), "StatusMsg", "StatusMsg", 1), `&`, ``, 1) + `,`,
		`Stream:` + repeatedStringForStream + `,`,
		`}`,
	}, "")
	return s
}
func (this *Operator) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForStream := "[]StreamMsg{"
	for _, f := range this.Stream {
		repeatedStringForStream += strings.Replace(strings.Replace(f.String(), "StreamMsg", "StreamMsg", 1), `&`, ``, 1) + ","
	}
	repeatedStringForStream += "}"
	repeatedStringForEvents := "[]EventMsg{"
	for _, f := range this.Events {
		repeatedStringForEvents += strings.Replace(strings.Replace(f.String(), "EventMsg", "EventMsg", 1), `&`, ``, 1) + ","
	}
	repeatedStringForEvents += "}"
	s := strings.Join([]string{`&Operator{`,
		`Timestamp:` + fmt.Sprintf("%v", this.Timestamp) + `,`,
		`OWD:` + fmt.Sprintf("%v", this.OWD) + `,`,
		`Stream:` + repeatedStringForStream + `,`,
		`Events:` + repeatedStringForEvents + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringSchema(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *StreamMsg) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSchema
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StreamMsg: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StreamMsg: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchema
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= StreamType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchema
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSchema
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSchema
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Data.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSchema(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSchema
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StatusMsg) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSchema
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StatusMsg: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StatusMsg: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OWD", wireType)
			}
			m.OWD = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchema
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OWD |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RTT", wireType)
			}
			m.RTT = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchema
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RTT |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Jitter", wireType)
			}
			m.Jitter = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchema
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Jitter |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Battery", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint32(encoding_binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
			m.Battery = float32(math.Float32frombits(v))
		case 5:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Health", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint32(encoding_binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
			m.Health = float32(math.Float32frombits(v))
		default:
			iNdEx = preIndex
			skippy, err := skipSchema(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSchema
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ChatMsg) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSchema
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ChatMsg: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ChatMsg: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchema
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Username", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchema
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSchema
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSchema
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Username = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Message", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchema
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSchema
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSchema
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Message = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSchema(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSchema
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventMsg) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSchema
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventMsg: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventMsg: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchema
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowSchema
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Flags = append(m.Flags, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowSchema
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthSchema
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthSchema
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.Flags) == 0 {
					m.Flags = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowSchema
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Flags = append(m.Flags, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Flags", wireType)
			}
		case 3:
			if wireType == 5 {
				var v uint32
				if (iNdEx + 4) > l {
					return io.ErrUnexpectedEOF
				}
				v = uint32(encoding_binary.LittleEndian.Uint32(dAtA[iNdEx:]))
				iNdEx += 4
				v2 := float32(math.Float32frombits(v))
				m.Data = append(m.Data, v2)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowSchema
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthSchema
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthSchema
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				elementCount = packedLen / 4
				if elementCount != 0 && len(m.Data) == 0 {
					m.Data = make([]float32, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint32
					if (iNdEx + 4) > l {
						return io.ErrUnexpectedEOF
					}
					v = uint32(encoding_binary.LittleEndian.Uint32(dAtA[iNdEx:]))
					iNdEx += 4
					v2 := float32(math.Float32frombits(v))
					m.Data = append(m.Data, v2)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSchema(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSchema
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RobotMsg) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSchema
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RobotMsg: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RobotMsg: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchema
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSchema
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSchema
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchema
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSchema
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSchema
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchema
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSchema
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSchema
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Capabilities", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchema
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSchema
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSchema
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Capabilities = append(m.Capabilities, RobotMsg_Capability{})
			if err := m.Capabilities[len(m.Capabilities)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSchema(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSchema
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RobotMsg_Capability) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSchema
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Capability: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Capability: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchema
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchema
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSchema
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSchema
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchema
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSchema
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSchema
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSchema(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSchema
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Robot) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSchema
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Robot: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Robot: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchema
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Robot", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchema
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSchema
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSchema
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Robot.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchema
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSchema
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSchema
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Status.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Stream", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchema
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSchema
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSchema
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Stream = append(m.Stream, StreamMsg{})
			if err := m.Stream[len(m.Stream)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSchema(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSchema
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Operator) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSchema
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Operator: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Operator: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchema
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OWD", wireType)
			}
			m.OWD = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchema
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OWD |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Stream", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchema
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSchema
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSchema
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Stream = append(m.Stream, StreamMsg{})
			if err := m.Stream[len(m.Stream)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Events", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchema
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSchema
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSchema
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Events = append(m.Events, EventMsg{})
			if err := m.Events[len(m.Events)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSchema(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSchema
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSchema(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSchema
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSchema
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSchema
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSchema
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSchema
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSchema
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSchema        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSchema          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSchema = fmt.Errorf("proto: unexpected end of group")
)
