version: '3'

services:
  db:
    image: postgres
    expose:
        - 5432
    environment:
        POSTGRES_USER: $DB_USER
        POSTGRES_PASSWORD: $DB_PASS
        POSTGRES_DB: $DB_NAME
    volumes:
        - ./tmp/pg:/var/lib/postgresql/data

  nats:
    image: nats:latest
    ports:
      - 6222:6222
      - 4222:4222
      - 8222:8222

  app:
    build: 
      context: .
      dockerfile: dev.Dockerfile
    # command: -- go run backend/cmd/gateway/main.go
    #command: --verbose --trigger -- go run backend/cmd/gateway/main.go
    command:  --verbose --trigger -- go build backend/cmd/gateway/main.go -- ./main
    env_file: .env
    volumes:
      - ./backend:/src/backend
      - ./schema:/src/schema
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - db
      - nats

  governor:
    build: 
      context: .
      dockerfile: dev.Dockerfile
    command:  --trigger -- go build backend/cmd/governor/main.go -- ./main
    env_file: .env
    volumes:
      - ./backend:/src/backend
      - ./schema:/src/schema
    depends_on:
      - db
      - nats

  spa:
    build: 
      context: .
      dockerfile: frontend/dev.Dockerfile
    environment:
      API_URL: http://app:8080/api
    volumes:
      - ./frontend/src:/src/src
    ports:
      - 3000:8080
    depends_on:
      - db
      - app

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - db
